### ISSUE TITLE
To do list for the Starterkit 2018

### ISSUE THREAD

**Issue by dberzano** [alidock/alidock#6]
- [x] Configuration file (#16)
- [x] Update container (#24)
- [x] Update script (#10)
- [x] `.bashrc` & friends (#7)
- [x] Make commands stable (#9)
- [x] Automatic container generation & push (#15)
- [x] Documentation (alice-doc/alice-analysis-tutorial#51)
- [x] Add `tmux` integration (#8)
- [x] Admin mode as in `alidock root` (#7)
- [x] Automatic deployment on pypi (#12)
- [x] Fix `aliBuild init` problem (relative paths)
- [x] Support multiple users (#17)
- [x] Prevent execution from `root` (#17)
- [x] No tmux from inside tmux (#17)
- [x] Run command in the container from cmdline (needed for VSCode integration in tutorial) (#19)
- [x] Create automatic builds for AliPhysics on CC7 to fill cache

**Comment by mconcas** [comment]
I am pretty sure you remember that, but there should be a custom flag to pass docker to avoid cvmfs to become unusable inside the container

**Comment by dberzano** [comment]
@mconcas I have commented on #11, now closed. Passing the custom flag makes it work. But it breaks `alidock` completely on macOS, as in: the container won't start at all. CVMFS is not urgent, and should be a config option.

**Comment by dberzano** [comment]
I have just added a bullet on the installation of alidock. We essentially need some lines that make it work everywhere.

The experienced user can extrapolate all the required information from `pip install alidock`, and we would like not to install anything as root.

One option is:

```bash
# in .bashrc
export PYTHONUSERBASE="$HOME/.localpython"
export PATH="$PYTHONUSERBASE/bin:$PATH"

# installation (normal user)
pip install --user alidock
```

Problems:

* Only one `PYTHONUSERBASE` is allowed, cannot append path.
* Option `--user` needs to be specified.
* If switching between different Python versions, the dir will stay the same and this will create problems.

Another option is to use `PYTHONPATH`. Even if not set, `pip install` has a default user path, however the `bin` directory is not in the `PATH`.

**Comment by dberzano** [comment]
Documentation should mention how to add a user to the `docker` group. And `alidock` should refuse `ssh`ing as `root` (you cannot run `alidock` as `root`).

**Comment by dberzano** [comment]
This is to say that we have nightly-produced cached builds for Run 2 sw.
